exclude: '^serveur/chroma_db/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:

    -   id: check-yaml          # Vérifie la syntaxe des fichiers YAML
    -   id: end-of-file-fixer   # Assure une ligne vide en fin de fichier
    -   id: trailing-whitespace # Supprime les espaces en fin de ligne
    -   id: check-added-large-files # Empêche de commit de gros fichiers par erreur

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black # Force un style de code parfait

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8 # Détecte les erreurs de logique et de style
        args: ["--max-line-length=88", "--extend-ignore=E203"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy # Vérifie la cohérence des types (Python)
        additional_dependencies: [types-requests]
