version: '3.8'

services:
  # Service 1 : L'entrée
  gateway:
    build: .mdevillet31/gateway
    ports:
      - "8080:5000"
    depends_on:
      - storage

  # Service 2 : La logique de stockage
  storage:
    build: .mdevillet31/storage
    depends_on:
      - db
  # Service 3 : La base de données
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: capsule_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data