name: Start VM

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: clone repository
      uses: actions/checkout@v4

    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: run test sécurité
      run: |
          pip install bandit
          bandit -r ./serveur
      continue-on-error: true

    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push docker image gateway
      uses: docker/build-push-action@v5
      with:
        context: ./serveur/gateway
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gateway

    - name: build and push docker image storage
      uses: docker/build-push-action@v5
      with:
        context: ./serveur/storage
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/storage
